name: CI/CD Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python Hello
        run: |
          echo "Running CI pipeline..."
          python -c "import hello; print(hello.handler())"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List S3 Buckets
        run: aws s3 ls

      - name: List Lambda Functions
        run: aws lambda list-functions --query 'Functions[*].FunctionName' --output table

      - name: List Glue Jobs
        run: aws glue list-jobs --output table
